# netlify.toml (minimal, known-good)

[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# ——— OAuth redirects (very specific, with force) ———
[[redirects]]
  from = "/auth/youtube"
  to   = "/.netlify/functions/youtube-oauth"
  status = 200
  force  = true

[[redirects]]
  from = "/auth/youtube/callback"
  to   = "/.netlify/functions/youtube-callback"
  status = 200
  force  = true
