name = "autostreampro-pages"
pages_build_output_dir = "."

# Needed for using libraries like @supabase/ssr in a Pages Function
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]
