name: Deploy to Cloudflare Pages (existing project)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - run: npm ci

      - run: npm i -g wrangler@4

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler pages deploy . \
            --project-name autostreampro-pages \
            --branch "${{ github.ref_name }}" \
            --commit-hash "${{ github.sha }}" \
            --commit-message "CI deploy from GitHub Actions"
